sudo: false
language: node_js

install:
- npm install npm@2.9.1
- ./node_modules/.bin/npm install

cache:
  directories:
  - node_modules

script: npm run ci

deploy:
  provider: s3
  access_key_id: AKIAIXRQBN5223M74JDA
  secret_access_key: xCrBWhV2UmxTM/fi1btUcwZgASTdTLaVGgZVOSr+
  bucket: hx-production-repo
  skip_cleanup: true
  region: eu-west-1
  local-dir: example
  upload-dir: react-car-reg
  acl: public_read
  on:
    branch: master
