sudo: false
language: node_js

install:
- npm install npm@2.9.1
- ./node_modules/.bin/npm install

cache:
  directories:
  - node_modules

script: npm run ci

deploy:
  provider: s3
  access_key_id: AKIAIXRQBN5223M74JDA
  secret_access_key:
    secure: VWTpaHuR3ZMxQPiNyNsSJ3EuOQavIgQugyzSeyE83OrCImAIDlqpw/2OGElOgzHxqqy4nUnNXEKmad1hANGphH+DyzlowODqaO9fn94RcwrMGWluJW4iLWovezLqESRR1XQyMD/iouiVkVbaY5eo5QnTm5iMIuLHwY3yUwSkFN82waUllIHhHJ8qnKQi/tmx2J2IGkHnikKlaGaDcO5SaZqyshAnGu0svpv/3YktTf/tzZH1vRBp8dYppyISSa3shHjiWBopPvs782youafbBQw768s55QqzdZEGLpRAf1SJJ3rG4gEFsjofRmtXyB+P/vT2ZnVus4IkVNf4v9PVp0N//SPLX3ApXKTeli1kTIdoE+u7iUL866Kq58oCqijsTSfW0HvzQ5hZJusIcsm3st1d3wW09DXEN/RxJODu4JUCHv58F60xlgp8mgylFoBK7V4VZ8uWkpOB5b9fEsnoF3BTETlz4LZGRBcjYnb7GH7Yab9nxOrdelPWtWV/+dLwS2F+UBF0s6n9+jHDA14oVT4PNHJ1c7XnuCqf+lrVuySWZsUvyRS13hPnAeEN8IsyvtRit74winf9jUTfJIuv765X4e0JwVg3+EshqJ1HmthUCu2Pafq5AjTvZ9kToXCgKuwlp/J0fSIAtrMbeAPSr2joLXDW570CskFPZ0Lkl4E=
  bucket: hx-production-repo
  skip_cleanup: true
  region: eu-west-1
  upload-dir: react-car-reg
  upload_dir: react-car-reg
  acl: public_read
  on:
    branch: master
