sudo: false
language: node_js
install:
- npm install npm@2.9.1
- ./node_modules/.bin/npm install
cache:
  directories:
  - node_modules
script: npm run ci
deploy:
  provider: s3
  access_key_id: AKIAJBKWFTK2WOXCD5MQ
  secret_access_key:
    secure: FQmqBlK8Fykj8hN5mUX/FdSNCnqX9dUNSuI/052TRDt64Wm/iIYs/HS7f2Qs68SdCSpDqzW2viG4Aoz2hLvnDPeLpUsLLeRRDzm6vQ2svKxm+xV4M1RRO1JjL1bRXWXeekb0D9C4aRlbzN38TtEPJ2K3IoiKz0OAlzUMCVyKrF9reoFrKDyYQdnEr+Kg1tGLZb3XQRUVAWg7lzY2zcUGFjgTYBsbu1gUKZ/3PV/4pT+XdpAGWLFDrGVaPBX8AiRaPBRgFySKDga+Oev2vitwzeIh7VBijkkIvjeQYUR9v2A5uQu5mPLmi/B0bDTEAi5MbPNKa1Ugqve/6WsRA8tctnp3wqsMA4vzBWgTQ2jQzC297QPDzO8afwNYrUiZOgmXMYXYH5r+vK6/DHK8ORDbHNi5S0PBvYnSCUMyxfWPiaeoQ2tVUPk/SEeJEV2hOny8TRxhvcvjWR4Y9lkvNkxl8izkOWLlGMtRjblIfyzoEsO0Ra5Q057ldEpj73kn/IAIvsb1dX7KctggaHakdEEQ4vPInOkuzgt/h/lLsx2mumnH2DlYexwtWAMle37GWY/QlNy3XsH28cG/+rJKDydrgcm85XWlRZY6vKRG/r72VGQfn3b9r+lDaorI07MrlzBKEtQHi1hYd8GA53lRUgsxmhmzbgzGMz/iZZ/t5UcAm74=
  bucket: hx-production-repo
  skip_cleanup: true
  region: eu-west-1
  upload-dir: react-car-reg
  upload_dir: react-car-reg
  acl: public_read
  on:
    branch: master
